<a href="https://colab.research.google.com/github/Pankajkalbande/DiseasePrediction-Of-Stroke-Diabetiese-and-Hypertension/blob/main/Disease_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
data = pd.read_csv('Patients Data Classified.csv')

In [ ]:
data.describe()

Patient Number         Age  ...  Gum Bleeding  Abdominal Pain
count      103.000000  103.000000  ...    103.000000      103.000000
mean        52.000000   52.961165  ...      0.009709        0.009709
std         29.877528   14.236739  ...      0.098533        0.098533
min          1.000000   20.000000  ...      0.000000        0.000000
25%         26.500000   44.500000  ...      0.000000        0.000000
50%         52.000000   54.000000  ...      0.000000        0.000000
75%         77.500000   62.500000  ...      0.000000        0.000000
max        103.000000   95.000000  ...      1.000000        1.000000

[8 rows x 40 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 43 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   Patient Number                               103 non-null    int64  
 1   Gender                                       103 non-null    object 
 2   Age                                          103 non-null    int64  
 3   Left sided paralysis                         103 non-null    int64  
 4   Right sided paralysis                        103 non-null    int64  
 5   Unable to speak                              103 non-null    int64  
 6   Unconsciousness                              103 non-null    int64  
 7   Deviation of Mouth                           103 non-null    int64  
 8   Slurring of Speech                           103 non-null    int64  
 9   Increased Number of Urination                103 non-null    int64  
 10  In

In [ ]:
data.head()

Patient Number Gender  Age  ...  Abdominal Pain  Output   Suggested Doctor
0               1   Male   52  ...               0   Stroke       Neurologist
1               2   Male   55  ...               0   Stroke       Neurologist
2               3   Male   95  ...               0   Stroke       Neurologist
3               4   Male   55  ...               0   Stroke       Neurologist
4               5   Male   56  ...               0   Stroke       Neurologist

[5 rows x 43 columns]

In [ ]:
# Preprocessing

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder=LabelEncoder()
data.Gender=encoder.fit_transform(data.Gender)
data.head()

Patient Number  Gender  Age  ...  Abdominal Pain  Output   Suggested Doctor
0               1       1   52  ...               0   Stroke       Neurologist
1               2       1   55  ...               0   Stroke       Neurologist
2               3       1   95  ...               0   Stroke       Neurologist
3               4       1   55  ...               0   Stroke       Neurologist
4               5       1   56  ...               0   Stroke       Neurologist

[5 rows x 43 columns]

In [ ]:
data

Patient Number  Gender  Age  ...  Abdominal Pain       Output   Suggested Doctor
0                 1       1   52  ...               0        Stroke       Neurologist
1                 2       1   55  ...               0        Stroke       Neurologist
2                 3       1   95  ...               0        Stroke       Neurologist
3                 4       1   55  ...               0        Stroke       Neurologist
4                 5       1   56  ...               0        Stroke       Neurologist
..              ...     ...  ...  ...             ...           ...               ...
98               99       1   60  ...               0  Blood Cancer        Oncologist
99              100       0   50  ...               0  Blood Cancer        Oncologist
100             101       0   21  ...               0  Blood Cancer        Oncologist
101             102       0   32  ...               1  Blood Cancer        Oncologist
102             103       0   30  ...               0  Blood Cancer        Oncologist

[103 rows x 43 columns]

In [ ]:
# Feature Selection

In [ ]:
data=data.drop(columns=['Patient Number'])

In [ ]:
data.head()

Gender  Age  Left sided paralysis   ...  Abdominal Pain  Output   Suggested Doctor
0       1   52                      1  ...               0   Stroke       Neurologist
1       1   55                      0  ...               0   Stroke       Neurologist
2       1   95                      1  ...               0   Stroke       Neurologist
3       1   55                      1  ...               0   Stroke       Neurologist
4       1   56                      0  ...               0   Stroke       Neurologist

[5 rows x 42 columns]

In [ ]:
#X=data.drop(['Exited'], axis=1)
#y=data['Exited']

In [ ]:
X = data.iloc[:, 1:2].values
y = data.iloc[:, 2].values

In [ ]:
X

array([[52],
       [55],
       [95],
       [55],
       [56],
       [60],
       [70],
       [60],
       [59],
       [54],
       [66],
       [57],
       [62],
       [67],
       [58],
       [73],
       [51],
       [65],
       [53],
       [57],
       [78],
       [63],
       [49],
       [61],
       [54],
       [67],
       [56],
       [76],
       [73],
       [57],
       [67],
       [64],
       [50],
       [45],
       [48],
       [56],
       [60],
       [53],
       [47],
       [70],
       [64],
       [52],
       [38],
       [72],
       [49],
       [46],
       [40],
       [64],
       [51],
       [70],
       [35],
       [49],
       [32],
       [35],
       [60],
       [29],
       [56],
       [36],
       [30],
       [59],
       [40],
       [49],
       [60],
       [51],
       [45],
       [42],
       [30],
       [45],
       [32],
       [50],
       [70],
       [38],
       [71],
       [42],
       [61],
       [75],
       [72],

In [ ]:
y

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
classifier=KNeighborsClassifier(n_neighbors=10,metric='euclidean')

In [ ]:
classifier.fit(X_train, y_train)
# training model


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='euclidean',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [ ]:
pred= classifier.predict(X_test) #predicting 'Exited'

In [ ]:
from sklearn.metrics import (accuracy_score,confusion_matrix)

In [ ]:
accuracy_score(y_test,pred)

0.7142857142857143

In [ ]:
confusion_matrix(y_test,pred)

array([[15,  0],
       [ 6,  0]])